x-environments: &default
  env_file: .env # 기본 환경 파일을 지정합니다.
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    <<: *default

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass banchan201105
    container_name: redis
    ports:
      - "6379:6379"
    <<: *default
    volumes:
      - ./redis_data:/data
      - ./redis_data/redis.conf:/usr/local/etc/redis/redis.conf

