spring:
  datasource:
    url: jdbc:mysql://localhost:3306/passkeyauth
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

spring.data.redis:
  host: localhost # Redis 서버 호스트
  port: 6379 # Redis 서버 포트
  password: banchan201105 # Redis 서버 비밀번호


server:
  port: 8080
  servlet:
    session:
      timeout: 30m

rp:
  id: localhost
  name: Passkey Auth Example
  origin: http://localhost:3000